### ISSUE TITLE
Can't find train.csv in your jupyter notebook

### ISSUE THREAD

**Issue by LalitNM** [aditya-sarkar441/Multivariate-regression#1]
I can't find the train.csv file mentioned in [file](https://github.com/aditya-sarkar441/Multivariate-regression/blob/master/neural%20nets.ipynb). Will you please upload this.

**Comment by aditya-sarkar441** [comment]
It's not complete yet. However, you can find data here https://www.kaggle.com/c/titanic

**Comment by LalitNM** [comment]
can't you upload whole data set.
